import './globals.css'
import { Jost } from 'next/font/google'
import Header from '@/app/components/header'
import FixMobileVH from '@/app/components/fix-mobile-vh'

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={jost.className} style={{ height: '300vh' }}>
        <FixMobileVH />
        <Header />
        {children}
      </body>
    </html>
  )
}
